### ISSUE TITLE
SSL errors can occur when downloading files from github in a corporate environment that decrypts traffic

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc-tools#62]
qpc-tools downloads two files from github during installation.  The download methods were implemented differently and one tolerates corporate signed certs and the other does not.

### Fails with SSL error
```
- name: Download Quipucords server container image from GitHub
  get_url:
    url: "{{ quipucords_server_container_image_url }}"
    dest: "{{ server_packages }}"
    tmp_dest: "{{ server_packages }}"
    mode: 0644
    timeout: 300
  when:
    - not quipucords_image_present
```

### No SSL errors
```
- name: Query GitHub for the latest release of Quipucords server
  uri:
    url: https://github.com/quipucords/quipucords/releases/latest/download/release_info.json
    validate_certs: no
    return_content: yes
  retries: 5
  delay: 5
  register: github_release_response
  until: github_release_response.status == 200 or github_release_response.status == 401
  changed_when: false
  when:
    - server_version is not defined
```
