### ISSUE TITLE
Error on using qpc-tools on Rhel 7.6 - can't find has_epel variable

### ISSUE THREAD

**Issue by justinkreft** [quipucords/qpc-tools#90]
Trying to install on RHEL 7.6 using after `yum install https://github.com/quipucords/qpc-tools/releases/latest/download/qpc-tools.el7.noarch.rpm` and then use `qpc-tools cli install`

It fails here:

```
TASK [cli : Install EPEL for CentOS/RHEL 6 from internet] *****************************
task path: /usr/lib/python3.6/site-packages/qpc_tools/cli/ansible/install/roles/cli/tasks/load_rpm_online.yml:19
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [cli : Install EPEL for CentOS/RHEL 7 from internet] *****************************
task path: /usr/lib/python3.6/site-packages/qpc_tools/cli/ansible/install/roles/cli/tasks/load_rpm_online.yml:28
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'not have_epel' failed. The error was: error while evaluating conditional (not have_epel): 'have_epel' is undefined\n\nThe error appears to have been in '/usr/lib/python3.6/site-packages/qpc_tools/cli/ansible/install/roles/cli/tasks/load_rpm_online.yml': line 28, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install EPEL for CentOS/RHEL 7 from internet\n  ^ here\n"}
	to retry, use: --limit @/usr/lib/python3.6/site-packages/qpc_tools/cli/ansible/install/playbook.retry
```

Is it because that `qpc_tools/cli/ansible/install/roles/cli/tasks/load_rpm_online.yml` at line 12?
```
- name: Set have_epel
  set_fact:
    have_epel: "{{ have_epel_raw.results[0].yumstate == 'installed' }}"
  when:
    - have_epel_raw["results"] is defined
    - have_epel_raw["results"]|length > 0
```
Conditions aren't being met and so the variable isn't set?

I did a `rpm -i epel-release-latest-7.noarch.rpm` and retried qpc-tools cli install and it worked. 
So I'm not blocked or anything but it seemed like the script was supposed to go acquire epel
